---

- name: disable sources.list
  replace:
    dest: '/etc/apt/sources.list'
    regexp: '^(deb.*)$'
    replace: '#\1'

- name: add repos
  apt_repository:
    repo={{ item }} state=present update_cache=yes
  with_items:
    - 'deb http://httpredir.debian.org/debian/ stretch main contrib non-free'
    - 'deb http://security.debian.org/ stretch/updates main contrib non-free'
    - 'deb http://httpredir.debian.org/debian/ stretch-updates main contrib non-free'

- name: update apt cache
  apt:
    cache_valid_time: 8600
    update_cache: yes

- name: dash config
  copy: >
    src=files/preseed/dash
    dest=/usr/local/src/preseed/
    owner=root mode=600
  register: dash_seed

- name: disable dash as default shell
  command: debconf-set-selections /usr/local/src/preseed/dash
  register: dash_reconf
  when: dash_seed.changed

- name: dash reconfigure
  command: dpkg-reconfigure -fnoninteractive dash
  when: dash_reconf.changed

- name: needed packages
  apt:
    name={{ item }} state=present
  with_items:
    - binutils
    - bup
    - certbot
    - ntp
    - ntpdate
    - python-virtualenv
    - python-pip
    - openvpn
    - rkhunter
    - sudo
    - python-pexpect
    - vim-nox
    - iputils-ping
    - traceroute
    - pbzip2
    - screen
    - tmux

- name: needed pip packages
  pip:
    name: pexpect
    state: latest
     

