---
- import_tasks: base.yml
- import_tasks: mail.yml
  when: ansible_hostname == "frrog01"
- import_tasks: mysql.yml
- import_tasks: webserver.yml
- import_tasks: ftp.yml
- import_tasks: stats.yml
- import_tasks: fail2ban.yml
- import_tasks: mailman.yml
  when: ansible_hostname =='frrog01'
  tags: mailman
- import_tasks: misc.yml
- import_tasks: iptables.yml
