---
- name: Install MySQL
  apt:
    name={{ item }}
  with_items:
    - mariadb-client
    - mariadb-server
    - python-mysqldb

- name: Start the MySQL service
  service:
    name: mysql
    state: started

- name: update mysql root password for all root accounts {{ ansible_hostname }}
  mysql_user: name=root host={{ item }} password={{ ispconfig[ansible_hostname].mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
    - 188.166.81.229
    - 172.77.70.1
  tags:
    mysql_password

- name: copy .my.cnf file with root password credentials
  template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags:
    mysql_password

- name: delete anonymous MySQL server user for $server_hostname
  mysql_user: user="" host="{{ server_hostname }}" state="absent"

- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"

- name: remove the MySQL test database
  mysql_db: db=test state=absent
