---
- name: restart postfix
  service: name=postfix state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart pureftpd
  systemd: name=pure-ftpd-mysql state=restarted
  
- name: restart php-fpm
  systemd: name=php{{ php_version }}-fpm state=restarted

